### ISSUE TITLE
Configurar projeto demo

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/laia#30]
Assim as pessoas poderão testar a ferramenta e entender um pouco melhor.

Deve ter um usuário padrão:

Usuário: acesso
Senha: paratodos@20

O link e as credenciais devem estar na documentação.

**Comment by anapaulagomes** [comment]
Criado: https://demo-laia.herokuapp.com/ ✅ 

Faltando apenas adicionar alguns pedidos de informação.

**Comment by anapaulagomes** [comment]
O usuário precisa ser marcado como "membro da equipe" para conseguir acessar o admin. Temos que destacar isso na página @turquetti.

**Comment by turquetti** [comment]
@anapaulagomes ok, vou fazer o ajuste na página!!!!

**Comment by anapaulagomes** [comment]
Tem alguns órgãos, um pedido e uma denúncia. O usuário e a senha estão funcionando. ✅
